### ISSUE TITLE
`shell::enter` executes too early before ` Systemd::fetch_or_create` finishing

### ISSUE THREAD

**Issue by vcheckzen** [Incisakura/Angea#2]
If I shutdown wsl with `wsl --shutdown` from windows, when first running `angea shell`, I would get the following error message.

```shell
$ angea shell
[1]    50 illegal hardware instruction  angea shell
```

The result is that I can not enter a new systemd shell util executing `angea shell` again.

I guess ` Systemd::fetch_or_create` is a async method, but I don't understand rust lang.

**Comment by incisakura** [comment]
`angea shell` has three steps: boot systemd if necessary, call dbus to start the shell, and forward pty data. 

If you are going to run `angea shell` when systemd is down, after calling `execve` to spawn systemd process, it actually needs some more time to complete systemd initiation. 
Angea would try to call dbus instantly after spawning systemd, but dbus/systemd is not available at this time. So error occurred.

This issue was fixed in 52ff7ceae260985b8bc2bfbc37c5ace3187ab689
https://github.com/Incisakura/angea/blob/a554cc67cb76bd730c474263791c2d21a55d285d/src/shell.rs#L68-L77

Please wait for the next release or try to build yourselfly on the latest commit.

**Comment by vcheckzen** [comment]
Glad to hear that and I compiled the latest code. However, when running `angea shell` this time, it gave me a `segmentation fault` hint:

```shell
$ ./angea
Angea v0.0.5
Usage: angea <command> [more]
Command:
    boot            Boot systemd as daemon
    shell [user]    Open a shell in container. Default: root
    shutdown        Kill running systemd
    help            This message
$ ./angea shell
[1]    844 segmentation fault  ./angea shell
```

I build the code in a `rust:alpine` docker container with `cargo build --release` command, I don't know if that is a proper compilation approach.

**Comment by vcheckzen** [comment]
But this issue is not a big problem for me now, cause I can use a shell wrapper to wait systemd initiation, looking forward to your next release.

**Comment by vcheckzen** [comment]
> I build the code in a rust:alpine docker container with cargo build --release command, I don't know if that is a proper compilation approach.

After switching to a debian-based docker image for compiling, the problem is gone.
